# This compose file is used to run the vizulizer

version: "3"

services:
  viz:
    # image: manomarks/visualizer
    image: manomarks/visualizer
    image: dockersamples/visualizer

    ports:
      - 3000:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints: [node.role == manager]
