version: '2'

networks:
  back:
    driver: overlay
  # bridge:
  #   external:
  #     name: bridge    
  # front:
  #   external:
  #     name: bridge

services:
  interlock:
    extends:
      file: haproxy.yml
      service: interlock
    # network_mode: "bridge"  
    # network_mode: "prod_back"
    environment:
      - "constraint:node==swarm-0"
    networks:
      back:

  haproxy:
    extends:
      file: haproxy.yml
      service: haproxy-server
    environment:
      - "constraint:node==swarm-0"
    # ports:
    #   - 80 
    # network_mode: "bridge"  
    # network_mode: "prod_back"
    # network_mode: "prod_front"
    # links:
    #   - interlock:interlock
    networks:
      - back
    # depends_on:
    #   - interlock

  web:
    image: alvinr/demo-webapp-vote:mariadb
    extends:
      file: haproxy.yml
      service: haproxy-app
    environment:
      MARIADB_HOST: mariadb
#      - "constraint:node!=swarm-0"      
    # networks:
    #   - back
    #   - bridge
    # network_mode: "bridge"  
    # network_mode: "prod_back"
    # network_mode: "prod_front"
    # links:
    #   - mariadb:mariadb
    networks:
      - back
    depends_on:
        - haproxy

  mariadb:
    extends:
      file: mariadb_base_cluster.yml
      service: mariadb
    image: mariadb:10.1.16
    environment:
      - "constraint:node==swarm-0"
    networks:
      back:
        aliases:
          - mariadb

  mariadb-shard1:
    extends:
      file: mariadb_base_cluster.yml
      service: mariadb-shard
    image: mariadb:10.1.16
    environment:
      - "affinity:com.mariadb.cluster!=prod-cluster"
    networks:
      back:
        aliases:
          - mariadb_shard1
    # links:
    #   - mariadb:mariadb
    depends_on:
        - mariadb

  mariadb-shard2:
    extends:
      file: mariadb_base_cluster.yml
      service: mariadb-shard
    image: mariadb:10.1.16
    environment:
      - "affinity:com.mariadb.cluster!=prod-cluster"
    networks:
      back:
        aliases:
          - mariadb_shard2
    # links:
    #   - mariadb:mariadb
    depends_on:
        - mariadb
