# This compose file is defines all the services required for a production deplyment
# - interlock: Used to listen for container create/destory events to automaticall reconfigure HAProxy
# - haproxy: Load balance between the Web Appliation nodes
# - web: Voting application
# - mariadb: Primary MariaDB node, which uses the Spider Storage Engine to distribiute reads/writes across the cluster
# - mariadb-shard1/2: Two shards that back the Spinder Storage Engine
#
# This uses the 'extends' primitive allowing decoration of the base service definitions.

version: '2'

networks:
  back:
    driver: overlay

services:
  interlock:
    extends:
      file: haproxy.yml
      service: interlock
    environment:
      - "constraint:node==swarm-0"
    networks:
      back:

  haproxy:
    extends:
      file: haproxy.yml
      service: haproxy-server
    environment:
      - "constraint:node==swarm-0"
    networks:
      - back

  web:
    image: alvinr/demo-webapp-vote:mariadb
    extends:
      file: haproxy.yml
      service: haproxy-app
    environment:
      MARIADB_HOST: mariadb
    networks:
      - back

  mariadb:
    extends:
      file: mariadb_base_cluster.yml
      service: mariadb
    image: mariadb:10.1.16
    environment:
      - "constraint:node==swarm-0"
    networks:
      back:
        aliases:
          - mariadb

  mariadb-shard1:
    extends:
      file: mariadb_base_cluster.yml
      service: mariadb-shard
    image: mariadb:10.1.16
    environment:
      - "affinity:com.mariadb.cluster!=prod-cluster"
    networks:
      back:
        aliases:
          - mariadb_shard1
    depends_on:
        - mariadb

  mariadb-shard2:
    extends:
      file: mariadb_base_cluster.yml
      service: mariadb-shard
    image: mariadb:10.1.16
    environment:
      - "affinity:com.mariadb.cluster!=prod-cluster"
    networks:
      back:
        aliases:
          - mariadb_shard2
    depends_on:
        - mariadb
