version: "2"

services:
  interlock:
    image: ehazlett/interlock:master
    command: run -c /etc/interlock/config.toml
    ports:
      - 8080
    volumes:
      - ./config.toml:/etc/interlock/config.toml
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/boot2docker:/etc/docker:ro
      - ./haproxy.cfg.template:/usr/local/etc/haproxy/haproxy.cfg.template:ro
    environment:
        INTERLOCK_CONFIG: |
            DockerURL = "${SWARM_HOST}"
            ListenAddr = ":8080"
            TLSCACert = "/etc/docker/ca.pem"
            TLSCert = "/etc/docker/server.pem"
            TLSKey = "/etc/docker/server-key.pem"
            [[Extensions]]
            Name = "haproxy"
            ConfigPath = "/usr/local/etc/haproxy/haproxy.cfg"
            PidPath = "/var/run/haproxy.pid"
            TemplatePath = "/usr/local/etc/haproxy/haproxy.cfg.template"
            MaxConn = 1024
            Port = 80
            AdminUser = "admin"
            AdminPass = "interlock"
            # BackendOverrideAddress = "172.17.0.1"

  haproxy-server:
    image: haproxy:latest
    ports:
      - 80:80
    labels:
      - "interlock.ext.name=haproxy"

  haproxy-app:
    ports:
      - 5000
    labels:
      - "interlock.hostname=prod"
      - "interlock.domain=myapp.com"