version: '2'

services:
    mariadb:
      image: mariadb:latest
      environment:
        MYSQL_ROOT_PASSWORD: foo
        "com.mariadb.cluster": prod-cluster
    #  volumes:
    #    - "$PWD:/var/lib/mysql"

    mariadb-shard:
      image: mariadb:latest
      environment:
        MYSQL_ROOT_PASSWORD: foo
        "com.mariadb.cluster": prod-cluster
    #  volumes:
    #    - "$PWD:/var/lib/mysql"