version: "3.1"
networks:
  front:
  back:
    external:
      name: myapp_back

secrets:
  app_password:
    file: ./app_password.txt
  mariadb_root_password:
    file: ./mariadb_password.txt
  xtrabackup_password:
    file: ./xtrabackup_password.txt

services:
  haproxy:
    image: dockercloud/haproxy
    networks:
      - front
      - back
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
    deploy:
      placement:
        constraints: [node.role == manager]

  web:
    image: alvinr/demo-webapp-vote:mariadb
    environment:
      SERVICE_PORTS: "5000"
      VIRTUAL_HOST: "prod.myapp.com"
      OPTION_A: "Support"
      OPTION_B: "Resist"
      OPTION_C: "Emigrate"
      APP_MARIADB_HOST: "maxscale"
      APP_USER: "app"
      APP_PASSWORD_FILE: "/run/secrets/app_password"
      APP_DATABASE: "test"
    networks:
      - back
    deploy:
      placement:
        constraints: [node.role != manger]
    secrets:
      - app_password

  mariadb_cluster:
    image: alvinr/mariadb-galera-swarm
    environment:
      MYSQL_ROOT_PASSWORD_FILE: "/run/secrets/mariadb_root_password"
      XTRABACKUP_PASSWORD_FILE: "/run/secrets/xtrabackup_password"
      CLUSTER_NAME: "mariadb_cluster"
      NODE_ADDRESS: "eth2"
      MYSQL_USER: "app"
      MYSQL_DATABASE: "test"
      MYSQL_PASSWORD_FILE: "/run/secrets/app_password"
      MAXSCALE_PRIVS: "true"
      TRACE: "y"
    labels:
      com.mariadb.cluster: "myapp-mariadb"
    networks:
      - back
    command: seed
    ports:
      - 3306:3306
      - 4567-4568:4567-4568
      - 4444:4444
    deploy:
      replicas: 1
      placement:
        constraints: [engine.labels.com.mariadb.cluster != myapp-mariadb]
    secrets:
      - mariadb_root_password
      - xtrabackup_password
      - app_password

  maxscale:
    image: alvinr/maxscale-swarm
    environment:
      DB_SERVICE_NAMES: "mariadb_cluster"
      # DB_SERVICE_NAMES: "myapp_mariadb_cluster myapp_mariadb_cluster_node"
      DB_TARGET_COUNT: "3"
      ENABLE_ROOT_USER: "false"
      MAX_USER: "app"
      MAX_PASS_FILE: "/run/secrets/app_password"
    labels:
      com.mariadb.cluster: "myapp-maxscale"
    networks:
      - back
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
      placement:
        constraints: [node.role == manager]
    secrets:
      - app_password
