# This compose file is used to create the schema required for the application

version: "3.1"

networks:
  back:
    external:
      name: myapp_back

secrets:
  app_password:
    file: ./app_password.txt

services:
  schema:
    image: alvinr/vote-schema:dev
    command: "-hmaxscale -uapp"
    networks:
      - back
    environment:
      MYSQL_PASSWORD_FILE: "/run/secrets/app_password"
    secrets:
      - app_password
