# This compose file is used to create the schema required for the application

version: '2'

networks:
  back:
    external:
      name: single_back

services:
  schema-setup:
    image: alvinr/vote-schema:dev
    command: "-hmariadb -uroot -pfoo"
    networks:
      - back    
    external_links:
      - single_mariadb_1:mariadb
