# This compose file defines the Application and Database services

version: "2"

services:
  web:
    build: .
    ports:
     - "5000:5000"
    links:
     - mariadb
    hostname: dev.myapp.com
    environment:
      APP_MARIADB_HOST: dev_mariadb_1
      APP_PASSWORD: foo   
  mariadb:
    image: mariadb:10.1
    environment:
      MYSQL_ROOT_PASSWORD: foo
  #  volumes: 
  #    - $PWD/data:/var/lib/mysql
