# This compose file is used to create the schema required for the application

version: '2'

services:
  schema-setup:
    image: alvinr/vote-schema:dev
    command: "-hmariadb -uroot -pfoo"
    external_links:
      - dev_mariadb_1:mariadb